@startuml

start

: массив ]
: счетчик ]
: ПРИСВОИТЬ счетчик_a\nначальное значение 0;
while (счетчик < 12) is (да)
	: введите_число <;
	: записываем число в массив
	: увеличить счетчик на 1;
endwhile (нет)
: инвертируем массив ]
: ПРИСВОИТЬ счетчик\nначальное значение 0;
: результат ]
: ПРИСВОИТЬ результат\nначальное значение 0;
while (счетчик < 12) is (да)
	:результат = sqrt(fabs(Х)) + 5 * pow(Х, 3);
'	if(результат > 400) is (да)'
'		: результат больше 400 >;

endwhile (нет)
: конец >

end

@enduml