@startuml

start

: массив_чисел ]
: счетчик ]
: ПРИСВОИТЬ счетчик_a\nначальное значение 0;
while (счетчик < 12) is (да)
	: введите_число <;
	: записываем число в массив
	: увеличить счетчик на 1;
endwhile (нет)
: инвертируем массив_чисел ]
: ПРИСВОИТЬ счетчик\nначальное значение 0;
: результат ]
: ПРИСВОИТЬ результат\nначальное значение 0;
: массив_значений ]
while (счетчик < 12) is (да)
	:результат = sqrt(fabs(Х)) + 5 * pow(Х, 3);
	:записываем результат в массив_значений;
endwhile (нет)
: ПРИСВОИТЬ счетчик\nначальное значение 0;

end

@enduml